Calendar_API/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('calendar_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('calendar_app.urls')),
]

calendar_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'calendar_app'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    url(r'^signup/$', views.SignUp.as_view(), name='signup'),
]

calendar_app/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime, date, time


# Create your models here.

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True)

    def get_start_time(self):
        return self.start_time.strftime('%H:%M')

    @property
    def get_html_url(self):
        url = reverse('calendar_app:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

calendar_app/forms.py
from django.forms import ModelForm, DateInput
from .models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    # отформатируем дату для отображения в datetime-local в HTML5
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # отформатируем дату для поля с датой из datetime-local HTML5
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

calendar_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime, date, timedelta
from django.contrib.auth.forms import UserCreationForm

from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils.safestring import mark_safe
from calendar import monthrange

from .models import Event
from .utils import Calendar
from .forms import EventForm


# Create your views here.

def index(request):
    return HttpResponse('hello')


class CalendarView(generic.ListView):
    model = Event
    template_name = 'calendar_app/cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # используем текущую дату для календаря
        # d = get_date(self.request.GET.get('day', None))
        d = get_date(self.request.GET.get('month', None))
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)

        # установим каендарь с текущим годом и датой
        cal = Calendar(d.year, d.month)

        # отформатируем календарь как table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        return context


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('calendar_app:calendar'))
    return render(request, 'calendar_app/cal/event.html', {'form': form})


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

calendar_app/templates/calendar_app/base.html
{% load staticfiles %}
<!doctype html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/calendar.css' %}">
    <title>Django Calendar App</title>
</head>
<body>

    {% block content %}    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

    {% block script %}    {% endblock %}
</body>
</html>

calendar_app/templates/calendar_app/cal/calendar.html
{% extends 'calendar_app/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="clearfix">
            <a class="btn btn-info logout" href="{% url 'logout' %}"> Logout </a>
            <p class="btn btn-info hello"> Hello, {{ user.username }}! </p>
        </div>
        <div class="clearfix">
            <a class="btn btn-info left" href="{% url 'calendar_app:calendar' %}?{{ prev_month }}"> Previous Month </a>
            <a class="btn btn-info right" href="{% url 'calendar_app:calendar' %}?{{ next_month }}"> Next Month </a>
            <a class="btn btn-info center" href="{% url 'calendar_app:event_new' %}?{{ event_new }}"> Create Event </a>
        </div>
        {{ calendar }}
    {% else %}
{#        <p>You are not logged in</p>#}
        <div class="clearfix">
            <a class="btn btn-info login"  href="{% url 'login' %}">Login</a>
            <a class="btn btn-info signup"  href="{% url 'calendar_app:signup' %}">Signup</a>
        </div>
    {% endif %}

{% endblock %}

calendar_app/templates/calendar_app/cal/event.html
{% extends 'calendar_app/base.html' %}

{% block title %} Event {% endblock %}

{% block content %}
    <div class="clearfix">
        <a class="btn btn-info left" href="{% url 'calendar_app:calendar' %}"> Calendar </a>
    </div>

    <form method="post">
        {% csrf_token %}
        <table class="form form-table">
            {{ form }}
            <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
        </table>
    </form>
{% endblock %}